# Generated by Django 2.2.3 on 2020-04-03 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(default='student', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default=' ', max_length=100)),
                ('start', models.CharField(default=' ', max_length=100)),
                ('end', models.CharField(default=' ', max_length=100)),
                ('parent_length', models.CharField(default=' ', max_length=100)),
                ('student_length', models.CharField(default=' ', max_length=100)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Ruser')),
            ],
        ),
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stpar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classnoadvisor', to='Home.Ruser')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classadvisor', to='Home.Ruser')),
            ],
        ),
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default=' ', max_length=1000)),
                ('status', models.CharField(default='0', max_length=10)),
                ('day', models.CharField(default=' ', max_length=100)),
                ('start', models.CharField(default=' ', max_length=100)),
                ('end', models.CharField(default=' ', max_length=100)),
                ('classroomi', models.ForeignKey(null=True, on_delete='CASCADE', to='Home.classroom')),
            ],
        ),
    ]
