# Generated by Django 2.2.3 on 2020-04-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='end',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advice',
            name='start',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='time',
            name='end',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='time',
            name='parent_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='time',
            name='start',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='time',
            name='student_length',
            field=models.IntegerField(default=0),
        ),
    ]
