# Generated by Django 2.2.3 on 2020-03-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200228_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='desc',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='advice',
            name='date',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='advice',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
