# Generated by Django 2.2.3 on 2020-04-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200406_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='time',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
