# Generated by Django 2.2.3 on 2020-04-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_advice_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
