# Generated by Django 2.2.3 on 2020-03-01 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200302_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
