# Generated by Django 2.2.3 on 2020-03-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20200302_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advice',
            name='date',
        ),
    ]
