# Generated by Django 2.2.3 on 2020-04-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20200407_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='score',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='classroom',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
