# Generated by Django 2.2.3 on 2020-04-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200408_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruser',
            name='code',
            field=models.CharField(default='free', max_length=20),
        ),
    ]
